# Generated by Django 3.0.5 on 2020-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitbook',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
