# Generated by Django 3.0.5 on 2020-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submit', '0002_submitbook_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitbook',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
